// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgId.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "msgId.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::EnumDescriptor* MessageID_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_msgId_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_msgId_2eproto() {
  protobuf_AddDesc_msgId_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "msgId.proto");
  GOOGLE_CHECK(file != NULL);
  MessageID_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_msgId_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_msgId_2eproto() {
}

void protobuf_AddDesc_msgId_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_msgId_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013msgId.proto*h\n\tMessageID\022\020\n\014MSGID__BEG"
    "IN\020\000\022\031\n\023MSGID_GAMEMSG_BEGIN\020\300\204=\022\025\n\017MSGID"
    "_FIRST_REQ\020\301\204=\022\027\n\021MSGID_GAMEMSG_END\020\200\211zb"
    "\006proto3", 127);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "msgId.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_msgId_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_msgId_2eproto {
  StaticDescriptorInitializer_msgId_2eproto() {
    protobuf_AddDesc_msgId_2eproto();
  }
} static_descriptor_initializer_msgId_2eproto_;
const ::google::protobuf::EnumDescriptor* MessageID_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageID_descriptor_;
}
bool MessageID_IsValid(int value) {
  switch(value) {
    case 0:
    case 1000000:
    case 1000001:
    case 2000000:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
