// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "player.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* Msg_Login_Req_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Msg_Login_Req_reflection_ = NULL;
const ::google::protobuf::Descriptor* Msg_Login_Ack_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Msg_Login_Ack_reflection_ = NULL;
const ::google::protobuf::Descriptor* Msg_CreatePlayer_Req_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Msg_CreatePlayer_Req_reflection_ = NULL;
const ::google::protobuf::Descriptor* Msg_CreatePlayer_Ack_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Msg_CreatePlayer_Ack_reflection_ = NULL;
const ::google::protobuf::Descriptor* Msg_LoginOff_Req_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Msg_LoginOff_Req_reflection_ = NULL;
const ::google::protobuf::Descriptor* Msg_LoginOff_Ack_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Msg_LoginOff_Ack_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_player_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_player_2eproto() {
  protobuf_AddDesc_player_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "player.proto");
  GOOGLE_CHECK(file != NULL);
  Msg_Login_Req_descriptor_ = file->message_type(0);
  static const int Msg_Login_Req_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_Login_Req, accountid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_Login_Req, roleid_),
  };
  Msg_Login_Req_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Msg_Login_Req_descriptor_,
      Msg_Login_Req::default_instance_,
      Msg_Login_Req_offsets_,
      -1,
      -1,
      -1,
      sizeof(Msg_Login_Req),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_Login_Req, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_Login_Req, _is_default_instance_));
  Msg_Login_Ack_descriptor_ = file->message_type(1);
  static const int Msg_Login_Ack_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_Login_Ack, returncode_),
  };
  Msg_Login_Ack_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Msg_Login_Ack_descriptor_,
      Msg_Login_Ack::default_instance_,
      Msg_Login_Ack_offsets_,
      -1,
      -1,
      -1,
      sizeof(Msg_Login_Ack),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_Login_Ack, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_Login_Ack, _is_default_instance_));
  Msg_CreatePlayer_Req_descriptor_ = file->message_type(2);
  static const int Msg_CreatePlayer_Req_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_CreatePlayer_Req, accountid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_CreatePlayer_Req, name_),
  };
  Msg_CreatePlayer_Req_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Msg_CreatePlayer_Req_descriptor_,
      Msg_CreatePlayer_Req::default_instance_,
      Msg_CreatePlayer_Req_offsets_,
      -1,
      -1,
      -1,
      sizeof(Msg_CreatePlayer_Req),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_CreatePlayer_Req, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_CreatePlayer_Req, _is_default_instance_));
  Msg_CreatePlayer_Ack_descriptor_ = file->message_type(3);
  static const int Msg_CreatePlayer_Ack_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_CreatePlayer_Ack, returncode_),
  };
  Msg_CreatePlayer_Ack_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Msg_CreatePlayer_Ack_descriptor_,
      Msg_CreatePlayer_Ack::default_instance_,
      Msg_CreatePlayer_Ack_offsets_,
      -1,
      -1,
      -1,
      sizeof(Msg_CreatePlayer_Ack),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_CreatePlayer_Ack, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_CreatePlayer_Ack, _is_default_instance_));
  Msg_LoginOff_Req_descriptor_ = file->message_type(4);
  static const int Msg_LoginOff_Req_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginOff_Req, roleid_),
  };
  Msg_LoginOff_Req_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Msg_LoginOff_Req_descriptor_,
      Msg_LoginOff_Req::default_instance_,
      Msg_LoginOff_Req_offsets_,
      -1,
      -1,
      -1,
      sizeof(Msg_LoginOff_Req),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginOff_Req, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginOff_Req, _is_default_instance_));
  Msg_LoginOff_Ack_descriptor_ = file->message_type(5);
  static const int Msg_LoginOff_Ack_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginOff_Ack, returncode_),
  };
  Msg_LoginOff_Ack_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Msg_LoginOff_Ack_descriptor_,
      Msg_LoginOff_Ack::default_instance_,
      Msg_LoginOff_Ack_offsets_,
      -1,
      -1,
      -1,
      sizeof(Msg_LoginOff_Ack),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginOff_Ack, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginOff_Ack, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_player_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Msg_Login_Req_descriptor_, &Msg_Login_Req::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Msg_Login_Ack_descriptor_, &Msg_Login_Ack::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Msg_CreatePlayer_Req_descriptor_, &Msg_CreatePlayer_Req::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Msg_CreatePlayer_Ack_descriptor_, &Msg_CreatePlayer_Ack::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Msg_LoginOff_Req_descriptor_, &Msg_LoginOff_Req::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Msg_LoginOff_Ack_descriptor_, &Msg_LoginOff_Ack::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_player_2eproto() {
  delete Msg_Login_Req::default_instance_;
  delete Msg_Login_Req_reflection_;
  delete Msg_Login_Ack::default_instance_;
  delete Msg_Login_Ack_reflection_;
  delete Msg_CreatePlayer_Req::default_instance_;
  delete Msg_CreatePlayer_Req_reflection_;
  delete Msg_CreatePlayer_Ack::default_instance_;
  delete Msg_CreatePlayer_Ack_reflection_;
  delete Msg_LoginOff_Req::default_instance_;
  delete Msg_LoginOff_Req_reflection_;
  delete Msg_LoginOff_Ack::default_instance_;
  delete Msg_LoginOff_Ack_reflection_;
}

void protobuf_AddDesc_player_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_player_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014player.proto\"2\n\rMsg_Login_Req\022\021\n\taccou"
    "ntid\030\001 \001(\r\022\016\n\006roleid\030\002 \001(\r\"#\n\rMsg_Login_"
    "Ack\022\022\n\nreturncode\030\001 \001(\005\"7\n\024Msg_CreatePla"
    "yer_Req\022\021\n\taccountid\030\001 \001(\005\022\014\n\004name\030\002 \001(\t"
    "\"*\n\024Msg_CreatePlayer_Ack\022\022\n\nreturncode\030\001"
    " \001(\005\"\"\n\020Msg_LoginOff_Req\022\016\n\006roleid\030\001 \001(\005"
    "\"&\n\020Msg_LoginOff_Ack\022\022\n\nreturncode\030\001 \001(\005"
    "b\006proto3", 288);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "player.proto", &protobuf_RegisterTypes);
  Msg_Login_Req::default_instance_ = new Msg_Login_Req();
  Msg_Login_Ack::default_instance_ = new Msg_Login_Ack();
  Msg_CreatePlayer_Req::default_instance_ = new Msg_CreatePlayer_Req();
  Msg_CreatePlayer_Ack::default_instance_ = new Msg_CreatePlayer_Ack();
  Msg_LoginOff_Req::default_instance_ = new Msg_LoginOff_Req();
  Msg_LoginOff_Ack::default_instance_ = new Msg_LoginOff_Ack();
  Msg_Login_Req::default_instance_->InitAsDefaultInstance();
  Msg_Login_Ack::default_instance_->InitAsDefaultInstance();
  Msg_CreatePlayer_Req::default_instance_->InitAsDefaultInstance();
  Msg_CreatePlayer_Ack::default_instance_->InitAsDefaultInstance();
  Msg_LoginOff_Req::default_instance_->InitAsDefaultInstance();
  Msg_LoginOff_Ack::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_player_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_player_2eproto {
  StaticDescriptorInitializer_player_2eproto() {
    protobuf_AddDesc_player_2eproto();
  }
} static_descriptor_initializer_player_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Msg_Login_Req::kAccountidFieldNumber;
const int Msg_Login_Req::kRoleidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Msg_Login_Req::Msg_Login_Req()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Msg_Login_Req)
}

void Msg_Login_Req::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Msg_Login_Req::Msg_Login_Req(const Msg_Login_Req& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Msg_Login_Req)
}

void Msg_Login_Req::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  accountid_ = 0u;
  roleid_ = 0u;
}

Msg_Login_Req::~Msg_Login_Req() {
  // @@protoc_insertion_point(destructor:Msg_Login_Req)
  SharedDtor();
}

void Msg_Login_Req::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Msg_Login_Req::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Msg_Login_Req::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Msg_Login_Req_descriptor_;
}

const Msg_Login_Req& Msg_Login_Req::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_player_2eproto();
  return *default_instance_;
}

Msg_Login_Req* Msg_Login_Req::default_instance_ = NULL;

Msg_Login_Req* Msg_Login_Req::New(::google::protobuf::Arena* arena) const {
  Msg_Login_Req* n = new Msg_Login_Req;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Msg_Login_Req::Clear() {
// @@protoc_insertion_point(message_clear_start:Msg_Login_Req)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(Msg_Login_Req, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<Msg_Login_Req*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(accountid_, roleid_);

#undef ZR_HELPER_
#undef ZR_

}

bool Msg_Login_Req::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Msg_Login_Req)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 accountid = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &accountid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_roleid;
        break;
      }

      // optional uint32 roleid = 2;
      case 2: {
        if (tag == 16) {
         parse_roleid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &roleid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Msg_Login_Req)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Msg_Login_Req)
  return false;
#undef DO_
}

void Msg_Login_Req::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Msg_Login_Req)
  // optional uint32 accountid = 1;
  if (this->accountid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->accountid(), output);
  }

  // optional uint32 roleid = 2;
  if (this->roleid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->roleid(), output);
  }

  // @@protoc_insertion_point(serialize_end:Msg_Login_Req)
}

::google::protobuf::uint8* Msg_Login_Req::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Msg_Login_Req)
  // optional uint32 accountid = 1;
  if (this->accountid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->accountid(), target);
  }

  // optional uint32 roleid = 2;
  if (this->roleid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->roleid(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Msg_Login_Req)
  return target;
}

int Msg_Login_Req::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Msg_Login_Req)
  int total_size = 0;

  // optional uint32 accountid = 1;
  if (this->accountid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->accountid());
  }

  // optional uint32 roleid = 2;
  if (this->roleid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->roleid());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Msg_Login_Req::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Msg_Login_Req)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Msg_Login_Req* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Msg_Login_Req>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Msg_Login_Req)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Msg_Login_Req)
    MergeFrom(*source);
  }
}

void Msg_Login_Req::MergeFrom(const Msg_Login_Req& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Msg_Login_Req)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.accountid() != 0) {
    set_accountid(from.accountid());
  }
  if (from.roleid() != 0) {
    set_roleid(from.roleid());
  }
}

void Msg_Login_Req::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Msg_Login_Req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Msg_Login_Req::CopyFrom(const Msg_Login_Req& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Msg_Login_Req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_Login_Req::IsInitialized() const {

  return true;
}

void Msg_Login_Req::Swap(Msg_Login_Req* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Msg_Login_Req::InternalSwap(Msg_Login_Req* other) {
  std::swap(accountid_, other->accountid_);
  std::swap(roleid_, other->roleid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Msg_Login_Req::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Msg_Login_Req_descriptor_;
  metadata.reflection = Msg_Login_Req_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Msg_Login_Req

// optional uint32 accountid = 1;
void Msg_Login_Req::clear_accountid() {
  accountid_ = 0u;
}
 ::google::protobuf::uint32 Msg_Login_Req::accountid() const {
  // @@protoc_insertion_point(field_get:Msg_Login_Req.accountid)
  return accountid_;
}
 void Msg_Login_Req::set_accountid(::google::protobuf::uint32 value) {
  
  accountid_ = value;
  // @@protoc_insertion_point(field_set:Msg_Login_Req.accountid)
}

// optional uint32 roleid = 2;
void Msg_Login_Req::clear_roleid() {
  roleid_ = 0u;
}
 ::google::protobuf::uint32 Msg_Login_Req::roleid() const {
  // @@protoc_insertion_point(field_get:Msg_Login_Req.roleid)
  return roleid_;
}
 void Msg_Login_Req::set_roleid(::google::protobuf::uint32 value) {
  
  roleid_ = value;
  // @@protoc_insertion_point(field_set:Msg_Login_Req.roleid)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Msg_Login_Ack::kReturncodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Msg_Login_Ack::Msg_Login_Ack()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Msg_Login_Ack)
}

void Msg_Login_Ack::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Msg_Login_Ack::Msg_Login_Ack(const Msg_Login_Ack& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Msg_Login_Ack)
}

void Msg_Login_Ack::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  returncode_ = 0;
}

Msg_Login_Ack::~Msg_Login_Ack() {
  // @@protoc_insertion_point(destructor:Msg_Login_Ack)
  SharedDtor();
}

void Msg_Login_Ack::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Msg_Login_Ack::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Msg_Login_Ack::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Msg_Login_Ack_descriptor_;
}

const Msg_Login_Ack& Msg_Login_Ack::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_player_2eproto();
  return *default_instance_;
}

Msg_Login_Ack* Msg_Login_Ack::default_instance_ = NULL;

Msg_Login_Ack* Msg_Login_Ack::New(::google::protobuf::Arena* arena) const {
  Msg_Login_Ack* n = new Msg_Login_Ack;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Msg_Login_Ack::Clear() {
// @@protoc_insertion_point(message_clear_start:Msg_Login_Ack)
  returncode_ = 0;
}

bool Msg_Login_Ack::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Msg_Login_Ack)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 returncode = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &returncode_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Msg_Login_Ack)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Msg_Login_Ack)
  return false;
#undef DO_
}

void Msg_Login_Ack::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Msg_Login_Ack)
  // optional int32 returncode = 1;
  if (this->returncode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->returncode(), output);
  }

  // @@protoc_insertion_point(serialize_end:Msg_Login_Ack)
}

::google::protobuf::uint8* Msg_Login_Ack::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Msg_Login_Ack)
  // optional int32 returncode = 1;
  if (this->returncode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->returncode(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Msg_Login_Ack)
  return target;
}

int Msg_Login_Ack::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Msg_Login_Ack)
  int total_size = 0;

  // optional int32 returncode = 1;
  if (this->returncode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->returncode());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Msg_Login_Ack::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Msg_Login_Ack)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Msg_Login_Ack* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Msg_Login_Ack>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Msg_Login_Ack)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Msg_Login_Ack)
    MergeFrom(*source);
  }
}

void Msg_Login_Ack::MergeFrom(const Msg_Login_Ack& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Msg_Login_Ack)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.returncode() != 0) {
    set_returncode(from.returncode());
  }
}

void Msg_Login_Ack::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Msg_Login_Ack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Msg_Login_Ack::CopyFrom(const Msg_Login_Ack& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Msg_Login_Ack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_Login_Ack::IsInitialized() const {

  return true;
}

void Msg_Login_Ack::Swap(Msg_Login_Ack* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Msg_Login_Ack::InternalSwap(Msg_Login_Ack* other) {
  std::swap(returncode_, other->returncode_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Msg_Login_Ack::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Msg_Login_Ack_descriptor_;
  metadata.reflection = Msg_Login_Ack_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Msg_Login_Ack

// optional int32 returncode = 1;
void Msg_Login_Ack::clear_returncode() {
  returncode_ = 0;
}
 ::google::protobuf::int32 Msg_Login_Ack::returncode() const {
  // @@protoc_insertion_point(field_get:Msg_Login_Ack.returncode)
  return returncode_;
}
 void Msg_Login_Ack::set_returncode(::google::protobuf::int32 value) {
  
  returncode_ = value;
  // @@protoc_insertion_point(field_set:Msg_Login_Ack.returncode)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Msg_CreatePlayer_Req::kAccountidFieldNumber;
const int Msg_CreatePlayer_Req::kNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Msg_CreatePlayer_Req::Msg_CreatePlayer_Req()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Msg_CreatePlayer_Req)
}

void Msg_CreatePlayer_Req::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Msg_CreatePlayer_Req::Msg_CreatePlayer_Req(const Msg_CreatePlayer_Req& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Msg_CreatePlayer_Req)
}

void Msg_CreatePlayer_Req::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  accountid_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Msg_CreatePlayer_Req::~Msg_CreatePlayer_Req() {
  // @@protoc_insertion_point(destructor:Msg_CreatePlayer_Req)
  SharedDtor();
}

void Msg_CreatePlayer_Req::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void Msg_CreatePlayer_Req::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Msg_CreatePlayer_Req::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Msg_CreatePlayer_Req_descriptor_;
}

const Msg_CreatePlayer_Req& Msg_CreatePlayer_Req::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_player_2eproto();
  return *default_instance_;
}

Msg_CreatePlayer_Req* Msg_CreatePlayer_Req::default_instance_ = NULL;

Msg_CreatePlayer_Req* Msg_CreatePlayer_Req::New(::google::protobuf::Arena* arena) const {
  Msg_CreatePlayer_Req* n = new Msg_CreatePlayer_Req;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Msg_CreatePlayer_Req::Clear() {
// @@protoc_insertion_point(message_clear_start:Msg_CreatePlayer_Req)
  accountid_ = 0;
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool Msg_CreatePlayer_Req::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Msg_CreatePlayer_Req)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 accountid = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &accountid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_name;
        break;
      }

      // optional string name = 2;
      case 2: {
        if (tag == 18) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Msg_CreatePlayer_Req.name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Msg_CreatePlayer_Req)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Msg_CreatePlayer_Req)
  return false;
#undef DO_
}

void Msg_CreatePlayer_Req::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Msg_CreatePlayer_Req)
  // optional int32 accountid = 1;
  if (this->accountid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->accountid(), output);
  }

  // optional string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Msg_CreatePlayer_Req.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->name(), output);
  }

  // @@protoc_insertion_point(serialize_end:Msg_CreatePlayer_Req)
}

::google::protobuf::uint8* Msg_CreatePlayer_Req::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Msg_CreatePlayer_Req)
  // optional int32 accountid = 1;
  if (this->accountid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->accountid(), target);
  }

  // optional string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Msg_CreatePlayer_Req.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Msg_CreatePlayer_Req)
  return target;
}

int Msg_CreatePlayer_Req::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Msg_CreatePlayer_Req)
  int total_size = 0;

  // optional int32 accountid = 1;
  if (this->accountid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->accountid());
  }

  // optional string name = 2;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Msg_CreatePlayer_Req::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Msg_CreatePlayer_Req)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Msg_CreatePlayer_Req* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Msg_CreatePlayer_Req>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Msg_CreatePlayer_Req)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Msg_CreatePlayer_Req)
    MergeFrom(*source);
  }
}

void Msg_CreatePlayer_Req::MergeFrom(const Msg_CreatePlayer_Req& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Msg_CreatePlayer_Req)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.accountid() != 0) {
    set_accountid(from.accountid());
  }
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
}

void Msg_CreatePlayer_Req::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Msg_CreatePlayer_Req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Msg_CreatePlayer_Req::CopyFrom(const Msg_CreatePlayer_Req& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Msg_CreatePlayer_Req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_CreatePlayer_Req::IsInitialized() const {

  return true;
}

void Msg_CreatePlayer_Req::Swap(Msg_CreatePlayer_Req* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Msg_CreatePlayer_Req::InternalSwap(Msg_CreatePlayer_Req* other) {
  std::swap(accountid_, other->accountid_);
  name_.Swap(&other->name_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Msg_CreatePlayer_Req::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Msg_CreatePlayer_Req_descriptor_;
  metadata.reflection = Msg_CreatePlayer_Req_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Msg_CreatePlayer_Req

// optional int32 accountid = 1;
void Msg_CreatePlayer_Req::clear_accountid() {
  accountid_ = 0;
}
 ::google::protobuf::int32 Msg_CreatePlayer_Req::accountid() const {
  // @@protoc_insertion_point(field_get:Msg_CreatePlayer_Req.accountid)
  return accountid_;
}
 void Msg_CreatePlayer_Req::set_accountid(::google::protobuf::int32 value) {
  
  accountid_ = value;
  // @@protoc_insertion_point(field_set:Msg_CreatePlayer_Req.accountid)
}

// optional string name = 2;
void Msg_CreatePlayer_Req::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Msg_CreatePlayer_Req::name() const {
  // @@protoc_insertion_point(field_get:Msg_CreatePlayer_Req.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Msg_CreatePlayer_Req::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Msg_CreatePlayer_Req.name)
}
 void Msg_CreatePlayer_Req::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Msg_CreatePlayer_Req.name)
}
 void Msg_CreatePlayer_Req::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Msg_CreatePlayer_Req.name)
}
 ::std::string* Msg_CreatePlayer_Req::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:Msg_CreatePlayer_Req.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Msg_CreatePlayer_Req::release_name() {
  // @@protoc_insertion_point(field_release:Msg_CreatePlayer_Req.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Msg_CreatePlayer_Req::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:Msg_CreatePlayer_Req.name)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Msg_CreatePlayer_Ack::kReturncodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Msg_CreatePlayer_Ack::Msg_CreatePlayer_Ack()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Msg_CreatePlayer_Ack)
}

void Msg_CreatePlayer_Ack::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Msg_CreatePlayer_Ack::Msg_CreatePlayer_Ack(const Msg_CreatePlayer_Ack& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Msg_CreatePlayer_Ack)
}

void Msg_CreatePlayer_Ack::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  returncode_ = 0;
}

Msg_CreatePlayer_Ack::~Msg_CreatePlayer_Ack() {
  // @@protoc_insertion_point(destructor:Msg_CreatePlayer_Ack)
  SharedDtor();
}

void Msg_CreatePlayer_Ack::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Msg_CreatePlayer_Ack::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Msg_CreatePlayer_Ack::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Msg_CreatePlayer_Ack_descriptor_;
}

const Msg_CreatePlayer_Ack& Msg_CreatePlayer_Ack::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_player_2eproto();
  return *default_instance_;
}

Msg_CreatePlayer_Ack* Msg_CreatePlayer_Ack::default_instance_ = NULL;

Msg_CreatePlayer_Ack* Msg_CreatePlayer_Ack::New(::google::protobuf::Arena* arena) const {
  Msg_CreatePlayer_Ack* n = new Msg_CreatePlayer_Ack;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Msg_CreatePlayer_Ack::Clear() {
// @@protoc_insertion_point(message_clear_start:Msg_CreatePlayer_Ack)
  returncode_ = 0;
}

bool Msg_CreatePlayer_Ack::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Msg_CreatePlayer_Ack)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 returncode = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &returncode_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Msg_CreatePlayer_Ack)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Msg_CreatePlayer_Ack)
  return false;
#undef DO_
}

void Msg_CreatePlayer_Ack::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Msg_CreatePlayer_Ack)
  // optional int32 returncode = 1;
  if (this->returncode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->returncode(), output);
  }

  // @@protoc_insertion_point(serialize_end:Msg_CreatePlayer_Ack)
}

::google::protobuf::uint8* Msg_CreatePlayer_Ack::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Msg_CreatePlayer_Ack)
  // optional int32 returncode = 1;
  if (this->returncode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->returncode(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Msg_CreatePlayer_Ack)
  return target;
}

int Msg_CreatePlayer_Ack::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Msg_CreatePlayer_Ack)
  int total_size = 0;

  // optional int32 returncode = 1;
  if (this->returncode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->returncode());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Msg_CreatePlayer_Ack::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Msg_CreatePlayer_Ack)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Msg_CreatePlayer_Ack* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Msg_CreatePlayer_Ack>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Msg_CreatePlayer_Ack)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Msg_CreatePlayer_Ack)
    MergeFrom(*source);
  }
}

void Msg_CreatePlayer_Ack::MergeFrom(const Msg_CreatePlayer_Ack& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Msg_CreatePlayer_Ack)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.returncode() != 0) {
    set_returncode(from.returncode());
  }
}

void Msg_CreatePlayer_Ack::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Msg_CreatePlayer_Ack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Msg_CreatePlayer_Ack::CopyFrom(const Msg_CreatePlayer_Ack& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Msg_CreatePlayer_Ack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_CreatePlayer_Ack::IsInitialized() const {

  return true;
}

void Msg_CreatePlayer_Ack::Swap(Msg_CreatePlayer_Ack* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Msg_CreatePlayer_Ack::InternalSwap(Msg_CreatePlayer_Ack* other) {
  std::swap(returncode_, other->returncode_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Msg_CreatePlayer_Ack::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Msg_CreatePlayer_Ack_descriptor_;
  metadata.reflection = Msg_CreatePlayer_Ack_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Msg_CreatePlayer_Ack

// optional int32 returncode = 1;
void Msg_CreatePlayer_Ack::clear_returncode() {
  returncode_ = 0;
}
 ::google::protobuf::int32 Msg_CreatePlayer_Ack::returncode() const {
  // @@protoc_insertion_point(field_get:Msg_CreatePlayer_Ack.returncode)
  return returncode_;
}
 void Msg_CreatePlayer_Ack::set_returncode(::google::protobuf::int32 value) {
  
  returncode_ = value;
  // @@protoc_insertion_point(field_set:Msg_CreatePlayer_Ack.returncode)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Msg_LoginOff_Req::kRoleidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Msg_LoginOff_Req::Msg_LoginOff_Req()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Msg_LoginOff_Req)
}

void Msg_LoginOff_Req::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Msg_LoginOff_Req::Msg_LoginOff_Req(const Msg_LoginOff_Req& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Msg_LoginOff_Req)
}

void Msg_LoginOff_Req::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  roleid_ = 0;
}

Msg_LoginOff_Req::~Msg_LoginOff_Req() {
  // @@protoc_insertion_point(destructor:Msg_LoginOff_Req)
  SharedDtor();
}

void Msg_LoginOff_Req::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Msg_LoginOff_Req::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Msg_LoginOff_Req::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Msg_LoginOff_Req_descriptor_;
}

const Msg_LoginOff_Req& Msg_LoginOff_Req::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_player_2eproto();
  return *default_instance_;
}

Msg_LoginOff_Req* Msg_LoginOff_Req::default_instance_ = NULL;

Msg_LoginOff_Req* Msg_LoginOff_Req::New(::google::protobuf::Arena* arena) const {
  Msg_LoginOff_Req* n = new Msg_LoginOff_Req;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Msg_LoginOff_Req::Clear() {
// @@protoc_insertion_point(message_clear_start:Msg_LoginOff_Req)
  roleid_ = 0;
}

bool Msg_LoginOff_Req::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Msg_LoginOff_Req)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 roleid = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &roleid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Msg_LoginOff_Req)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Msg_LoginOff_Req)
  return false;
#undef DO_
}

void Msg_LoginOff_Req::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Msg_LoginOff_Req)
  // optional int32 roleid = 1;
  if (this->roleid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->roleid(), output);
  }

  // @@protoc_insertion_point(serialize_end:Msg_LoginOff_Req)
}

::google::protobuf::uint8* Msg_LoginOff_Req::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Msg_LoginOff_Req)
  // optional int32 roleid = 1;
  if (this->roleid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->roleid(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Msg_LoginOff_Req)
  return target;
}

int Msg_LoginOff_Req::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Msg_LoginOff_Req)
  int total_size = 0;

  // optional int32 roleid = 1;
  if (this->roleid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->roleid());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Msg_LoginOff_Req::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Msg_LoginOff_Req)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Msg_LoginOff_Req* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Msg_LoginOff_Req>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Msg_LoginOff_Req)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Msg_LoginOff_Req)
    MergeFrom(*source);
  }
}

void Msg_LoginOff_Req::MergeFrom(const Msg_LoginOff_Req& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Msg_LoginOff_Req)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.roleid() != 0) {
    set_roleid(from.roleid());
  }
}

void Msg_LoginOff_Req::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Msg_LoginOff_Req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Msg_LoginOff_Req::CopyFrom(const Msg_LoginOff_Req& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Msg_LoginOff_Req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_LoginOff_Req::IsInitialized() const {

  return true;
}

void Msg_LoginOff_Req::Swap(Msg_LoginOff_Req* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Msg_LoginOff_Req::InternalSwap(Msg_LoginOff_Req* other) {
  std::swap(roleid_, other->roleid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Msg_LoginOff_Req::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Msg_LoginOff_Req_descriptor_;
  metadata.reflection = Msg_LoginOff_Req_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Msg_LoginOff_Req

// optional int32 roleid = 1;
void Msg_LoginOff_Req::clear_roleid() {
  roleid_ = 0;
}
 ::google::protobuf::int32 Msg_LoginOff_Req::roleid() const {
  // @@protoc_insertion_point(field_get:Msg_LoginOff_Req.roleid)
  return roleid_;
}
 void Msg_LoginOff_Req::set_roleid(::google::protobuf::int32 value) {
  
  roleid_ = value;
  // @@protoc_insertion_point(field_set:Msg_LoginOff_Req.roleid)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Msg_LoginOff_Ack::kReturncodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Msg_LoginOff_Ack::Msg_LoginOff_Ack()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Msg_LoginOff_Ack)
}

void Msg_LoginOff_Ack::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Msg_LoginOff_Ack::Msg_LoginOff_Ack(const Msg_LoginOff_Ack& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Msg_LoginOff_Ack)
}

void Msg_LoginOff_Ack::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  returncode_ = 0;
}

Msg_LoginOff_Ack::~Msg_LoginOff_Ack() {
  // @@protoc_insertion_point(destructor:Msg_LoginOff_Ack)
  SharedDtor();
}

void Msg_LoginOff_Ack::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Msg_LoginOff_Ack::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Msg_LoginOff_Ack::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Msg_LoginOff_Ack_descriptor_;
}

const Msg_LoginOff_Ack& Msg_LoginOff_Ack::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_player_2eproto();
  return *default_instance_;
}

Msg_LoginOff_Ack* Msg_LoginOff_Ack::default_instance_ = NULL;

Msg_LoginOff_Ack* Msg_LoginOff_Ack::New(::google::protobuf::Arena* arena) const {
  Msg_LoginOff_Ack* n = new Msg_LoginOff_Ack;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Msg_LoginOff_Ack::Clear() {
// @@protoc_insertion_point(message_clear_start:Msg_LoginOff_Ack)
  returncode_ = 0;
}

bool Msg_LoginOff_Ack::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Msg_LoginOff_Ack)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 returncode = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &returncode_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Msg_LoginOff_Ack)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Msg_LoginOff_Ack)
  return false;
#undef DO_
}

void Msg_LoginOff_Ack::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Msg_LoginOff_Ack)
  // optional int32 returncode = 1;
  if (this->returncode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->returncode(), output);
  }

  // @@protoc_insertion_point(serialize_end:Msg_LoginOff_Ack)
}

::google::protobuf::uint8* Msg_LoginOff_Ack::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Msg_LoginOff_Ack)
  // optional int32 returncode = 1;
  if (this->returncode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->returncode(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Msg_LoginOff_Ack)
  return target;
}

int Msg_LoginOff_Ack::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Msg_LoginOff_Ack)
  int total_size = 0;

  // optional int32 returncode = 1;
  if (this->returncode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->returncode());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Msg_LoginOff_Ack::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Msg_LoginOff_Ack)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Msg_LoginOff_Ack* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Msg_LoginOff_Ack>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Msg_LoginOff_Ack)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Msg_LoginOff_Ack)
    MergeFrom(*source);
  }
}

void Msg_LoginOff_Ack::MergeFrom(const Msg_LoginOff_Ack& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Msg_LoginOff_Ack)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.returncode() != 0) {
    set_returncode(from.returncode());
  }
}

void Msg_LoginOff_Ack::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Msg_LoginOff_Ack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Msg_LoginOff_Ack::CopyFrom(const Msg_LoginOff_Ack& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Msg_LoginOff_Ack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_LoginOff_Ack::IsInitialized() const {

  return true;
}

void Msg_LoginOff_Ack::Swap(Msg_LoginOff_Ack* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Msg_LoginOff_Ack::InternalSwap(Msg_LoginOff_Ack* other) {
  std::swap(returncode_, other->returncode_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Msg_LoginOff_Ack::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Msg_LoginOff_Ack_descriptor_;
  metadata.reflection = Msg_LoginOff_Ack_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Msg_LoginOff_Ack

// optional int32 returncode = 1;
void Msg_LoginOff_Ack::clear_returncode() {
  returncode_ = 0;
}
 ::google::protobuf::int32 Msg_LoginOff_Ack::returncode() const {
  // @@protoc_insertion_point(field_get:Msg_LoginOff_Ack.returncode)
  return returncode_;
}
 void Msg_LoginOff_Ack::set_returncode(::google::protobuf::int32 value) {
  
  returncode_ = value;
  // @@protoc_insertion_point(field_set:Msg_LoginOff_Ack.returncode)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
