// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "player.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* Msg_LoginAccount_Req_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Msg_LoginAccount_Req_reflection_ = NULL;
const ::google::protobuf::Descriptor* Msg_LoginAccount_Ack_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Msg_LoginAccount_Ack_reflection_ = NULL;
const ::google::protobuf::Descriptor* Msg_LoginPlayer_Req_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Msg_LoginPlayer_Req_reflection_ = NULL;
const ::google::protobuf::Descriptor* Msg_LoginPlayer_Ack_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Msg_LoginPlayer_Ack_reflection_ = NULL;
const ::google::protobuf::Descriptor* Msg_CreatePlayer_Req_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Msg_CreatePlayer_Req_reflection_ = NULL;
const ::google::protobuf::Descriptor* Msg_CreatePlayer_Ack_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Msg_CreatePlayer_Ack_reflection_ = NULL;
const ::google::protobuf::Descriptor* Msg_LoginOff_Req_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Msg_LoginOff_Req_reflection_ = NULL;
const ::google::protobuf::Descriptor* Msg_LoginOff_Ack_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Msg_LoginOff_Ack_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_player_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_player_2eproto() {
  protobuf_AddDesc_player_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "player.proto");
  GOOGLE_CHECK(file != NULL);
  Msg_LoginAccount_Req_descriptor_ = file->message_type(0);
  static const int Msg_LoginAccount_Req_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginAccount_Req, username_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginAccount_Req, password_),
  };
  Msg_LoginAccount_Req_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Msg_LoginAccount_Req_descriptor_,
      Msg_LoginAccount_Req::default_instance_,
      Msg_LoginAccount_Req_offsets_,
      -1,
      -1,
      -1,
      sizeof(Msg_LoginAccount_Req),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginAccount_Req, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginAccount_Req, _is_default_instance_));
  Msg_LoginAccount_Ack_descriptor_ = file->message_type(1);
  static const int Msg_LoginAccount_Ack_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginAccount_Ack, returncode_),
  };
  Msg_LoginAccount_Ack_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Msg_LoginAccount_Ack_descriptor_,
      Msg_LoginAccount_Ack::default_instance_,
      Msg_LoginAccount_Ack_offsets_,
      -1,
      -1,
      -1,
      sizeof(Msg_LoginAccount_Ack),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginAccount_Ack, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginAccount_Ack, _is_default_instance_));
  Msg_LoginPlayer_Req_descriptor_ = file->message_type(2);
  static const int Msg_LoginPlayer_Req_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginPlayer_Req, roleid_),
  };
  Msg_LoginPlayer_Req_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Msg_LoginPlayer_Req_descriptor_,
      Msg_LoginPlayer_Req::default_instance_,
      Msg_LoginPlayer_Req_offsets_,
      -1,
      -1,
      -1,
      sizeof(Msg_LoginPlayer_Req),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginPlayer_Req, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginPlayer_Req, _is_default_instance_));
  Msg_LoginPlayer_Ack_descriptor_ = file->message_type(3);
  static const int Msg_LoginPlayer_Ack_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginPlayer_Ack, returncode_),
  };
  Msg_LoginPlayer_Ack_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Msg_LoginPlayer_Ack_descriptor_,
      Msg_LoginPlayer_Ack::default_instance_,
      Msg_LoginPlayer_Ack_offsets_,
      -1,
      -1,
      -1,
      sizeof(Msg_LoginPlayer_Ack),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginPlayer_Ack, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginPlayer_Ack, _is_default_instance_));
  Msg_CreatePlayer_Req_descriptor_ = file->message_type(4);
  static const int Msg_CreatePlayer_Req_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_CreatePlayer_Req, accountid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_CreatePlayer_Req, name_),
  };
  Msg_CreatePlayer_Req_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Msg_CreatePlayer_Req_descriptor_,
      Msg_CreatePlayer_Req::default_instance_,
      Msg_CreatePlayer_Req_offsets_,
      -1,
      -1,
      -1,
      sizeof(Msg_CreatePlayer_Req),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_CreatePlayer_Req, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_CreatePlayer_Req, _is_default_instance_));
  Msg_CreatePlayer_Ack_descriptor_ = file->message_type(5);
  static const int Msg_CreatePlayer_Ack_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_CreatePlayer_Ack, returncode_),
  };
  Msg_CreatePlayer_Ack_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Msg_CreatePlayer_Ack_descriptor_,
      Msg_CreatePlayer_Ack::default_instance_,
      Msg_CreatePlayer_Ack_offsets_,
      -1,
      -1,
      -1,
      sizeof(Msg_CreatePlayer_Ack),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_CreatePlayer_Ack, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_CreatePlayer_Ack, _is_default_instance_));
  Msg_LoginOff_Req_descriptor_ = file->message_type(6);
  static const int Msg_LoginOff_Req_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginOff_Req, roleid_),
  };
  Msg_LoginOff_Req_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Msg_LoginOff_Req_descriptor_,
      Msg_LoginOff_Req::default_instance_,
      Msg_LoginOff_Req_offsets_,
      -1,
      -1,
      -1,
      sizeof(Msg_LoginOff_Req),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginOff_Req, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginOff_Req, _is_default_instance_));
  Msg_LoginOff_Ack_descriptor_ = file->message_type(7);
  static const int Msg_LoginOff_Ack_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginOff_Ack, returncode_),
  };
  Msg_LoginOff_Ack_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Msg_LoginOff_Ack_descriptor_,
      Msg_LoginOff_Ack::default_instance_,
      Msg_LoginOff_Ack_offsets_,
      -1,
      -1,
      -1,
      sizeof(Msg_LoginOff_Ack),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginOff_Ack, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Msg_LoginOff_Ack, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_player_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Msg_LoginAccount_Req_descriptor_, &Msg_LoginAccount_Req::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Msg_LoginAccount_Ack_descriptor_, &Msg_LoginAccount_Ack::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Msg_LoginPlayer_Req_descriptor_, &Msg_LoginPlayer_Req::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Msg_LoginPlayer_Ack_descriptor_, &Msg_LoginPlayer_Ack::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Msg_CreatePlayer_Req_descriptor_, &Msg_CreatePlayer_Req::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Msg_CreatePlayer_Ack_descriptor_, &Msg_CreatePlayer_Ack::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Msg_LoginOff_Req_descriptor_, &Msg_LoginOff_Req::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Msg_LoginOff_Ack_descriptor_, &Msg_LoginOff_Ack::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_player_2eproto() {
  delete Msg_LoginAccount_Req::default_instance_;
  delete Msg_LoginAccount_Req_reflection_;
  delete Msg_LoginAccount_Ack::default_instance_;
  delete Msg_LoginAccount_Ack_reflection_;
  delete Msg_LoginPlayer_Req::default_instance_;
  delete Msg_LoginPlayer_Req_reflection_;
  delete Msg_LoginPlayer_Ack::default_instance_;
  delete Msg_LoginPlayer_Ack_reflection_;
  delete Msg_CreatePlayer_Req::default_instance_;
  delete Msg_CreatePlayer_Req_reflection_;
  delete Msg_CreatePlayer_Ack::default_instance_;
  delete Msg_CreatePlayer_Ack_reflection_;
  delete Msg_LoginOff_Req::default_instance_;
  delete Msg_LoginOff_Req_reflection_;
  delete Msg_LoginOff_Ack::default_instance_;
  delete Msg_LoginOff_Ack_reflection_;
}

void protobuf_AddDesc_player_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_player_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014player.proto\":\n\024Msg_LoginAccount_Req\022\020"
    "\n\010username\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"*\n\024Ms"
    "g_LoginAccount_Ack\022\022\n\nreturncode\030\001 \001(\005\"%"
    "\n\023Msg_LoginPlayer_Req\022\016\n\006roleid\030\001 \001(\004\")\n"
    "\023Msg_LoginPlayer_Ack\022\022\n\nreturncode\030\001 \001(\005"
    "\"7\n\024Msg_CreatePlayer_Req\022\021\n\taccountid\030\001 "
    "\001(\005\022\014\n\004name\030\002 \001(\t\"*\n\024Msg_CreatePlayer_Ac"
    "k\022\022\n\nreturncode\030\001 \001(\005\"\"\n\020Msg_LoginOff_Re"
    "q\022\016\n\006roleid\030\001 \001(\005\"&\n\020Msg_LoginOff_Ack\022\022\n"
    "\nreturncode\030\001 \001(\005b\006proto3", 385);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "player.proto", &protobuf_RegisterTypes);
  Msg_LoginAccount_Req::default_instance_ = new Msg_LoginAccount_Req();
  Msg_LoginAccount_Ack::default_instance_ = new Msg_LoginAccount_Ack();
  Msg_LoginPlayer_Req::default_instance_ = new Msg_LoginPlayer_Req();
  Msg_LoginPlayer_Ack::default_instance_ = new Msg_LoginPlayer_Ack();
  Msg_CreatePlayer_Req::default_instance_ = new Msg_CreatePlayer_Req();
  Msg_CreatePlayer_Ack::default_instance_ = new Msg_CreatePlayer_Ack();
  Msg_LoginOff_Req::default_instance_ = new Msg_LoginOff_Req();
  Msg_LoginOff_Ack::default_instance_ = new Msg_LoginOff_Ack();
  Msg_LoginAccount_Req::default_instance_->InitAsDefaultInstance();
  Msg_LoginAccount_Ack::default_instance_->InitAsDefaultInstance();
  Msg_LoginPlayer_Req::default_instance_->InitAsDefaultInstance();
  Msg_LoginPlayer_Ack::default_instance_->InitAsDefaultInstance();
  Msg_CreatePlayer_Req::default_instance_->InitAsDefaultInstance();
  Msg_CreatePlayer_Ack::default_instance_->InitAsDefaultInstance();
  Msg_LoginOff_Req::default_instance_->InitAsDefaultInstance();
  Msg_LoginOff_Ack::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_player_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_player_2eproto {
  StaticDescriptorInitializer_player_2eproto() {
    protobuf_AddDesc_player_2eproto();
  }
} static_descriptor_initializer_player_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Msg_LoginAccount_Req::kUsernameFieldNumber;
const int Msg_LoginAccount_Req::kPasswordFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Msg_LoginAccount_Req::Msg_LoginAccount_Req()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Msg_LoginAccount_Req)
}

void Msg_LoginAccount_Req::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Msg_LoginAccount_Req::Msg_LoginAccount_Req(const Msg_LoginAccount_Req& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Msg_LoginAccount_Req)
}

void Msg_LoginAccount_Req::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  username_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Msg_LoginAccount_Req::~Msg_LoginAccount_Req() {
  // @@protoc_insertion_point(destructor:Msg_LoginAccount_Req)
  SharedDtor();
}

void Msg_LoginAccount_Req::SharedDtor() {
  username_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void Msg_LoginAccount_Req::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Msg_LoginAccount_Req::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Msg_LoginAccount_Req_descriptor_;
}

const Msg_LoginAccount_Req& Msg_LoginAccount_Req::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_player_2eproto();
  return *default_instance_;
}

Msg_LoginAccount_Req* Msg_LoginAccount_Req::default_instance_ = NULL;

Msg_LoginAccount_Req* Msg_LoginAccount_Req::New(::google::protobuf::Arena* arena) const {
  Msg_LoginAccount_Req* n = new Msg_LoginAccount_Req;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Msg_LoginAccount_Req::Clear() {
// @@protoc_insertion_point(message_clear_start:Msg_LoginAccount_Req)
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool Msg_LoginAccount_Req::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Msg_LoginAccount_Req)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string username = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_username()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->username().data(), this->username().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Msg_LoginAccount_Req.username"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_password;
        break;
      }

      // optional string password = 2;
      case 2: {
        if (tag == 18) {
         parse_password:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_password()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->password().data(), this->password().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Msg_LoginAccount_Req.password"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Msg_LoginAccount_Req)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Msg_LoginAccount_Req)
  return false;
#undef DO_
}

void Msg_LoginAccount_Req::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Msg_LoginAccount_Req)
  // optional string username = 1;
  if (this->username().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->username().data(), this->username().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Msg_LoginAccount_Req.username");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->username(), output);
  }

  // optional string password = 2;
  if (this->password().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->password().data(), this->password().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Msg_LoginAccount_Req.password");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->password(), output);
  }

  // @@protoc_insertion_point(serialize_end:Msg_LoginAccount_Req)
}

::google::protobuf::uint8* Msg_LoginAccount_Req::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Msg_LoginAccount_Req)
  // optional string username = 1;
  if (this->username().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->username().data(), this->username().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Msg_LoginAccount_Req.username");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->username(), target);
  }

  // optional string password = 2;
  if (this->password().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->password().data(), this->password().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Msg_LoginAccount_Req.password");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->password(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Msg_LoginAccount_Req)
  return target;
}

int Msg_LoginAccount_Req::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Msg_LoginAccount_Req)
  int total_size = 0;

  // optional string username = 1;
  if (this->username().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->username());
  }

  // optional string password = 2;
  if (this->password().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->password());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Msg_LoginAccount_Req::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Msg_LoginAccount_Req)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Msg_LoginAccount_Req* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Msg_LoginAccount_Req>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Msg_LoginAccount_Req)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Msg_LoginAccount_Req)
    MergeFrom(*source);
  }
}

void Msg_LoginAccount_Req::MergeFrom(const Msg_LoginAccount_Req& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Msg_LoginAccount_Req)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.username().size() > 0) {

    username_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.username_);
  }
  if (from.password().size() > 0) {

    password_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
}

void Msg_LoginAccount_Req::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Msg_LoginAccount_Req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Msg_LoginAccount_Req::CopyFrom(const Msg_LoginAccount_Req& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Msg_LoginAccount_Req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_LoginAccount_Req::IsInitialized() const {

  return true;
}

void Msg_LoginAccount_Req::Swap(Msg_LoginAccount_Req* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Msg_LoginAccount_Req::InternalSwap(Msg_LoginAccount_Req* other) {
  username_.Swap(&other->username_);
  password_.Swap(&other->password_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Msg_LoginAccount_Req::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Msg_LoginAccount_Req_descriptor_;
  metadata.reflection = Msg_LoginAccount_Req_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Msg_LoginAccount_Req

// optional string username = 1;
void Msg_LoginAccount_Req::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Msg_LoginAccount_Req::username() const {
  // @@protoc_insertion_point(field_get:Msg_LoginAccount_Req.username)
  return username_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Msg_LoginAccount_Req::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Msg_LoginAccount_Req.username)
}
 void Msg_LoginAccount_Req::set_username(const char* value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Msg_LoginAccount_Req.username)
}
 void Msg_LoginAccount_Req::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Msg_LoginAccount_Req.username)
}
 ::std::string* Msg_LoginAccount_Req::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:Msg_LoginAccount_Req.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Msg_LoginAccount_Req::release_username() {
  // @@protoc_insertion_point(field_release:Msg_LoginAccount_Req.username)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Msg_LoginAccount_Req::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:Msg_LoginAccount_Req.username)
}

// optional string password = 2;
void Msg_LoginAccount_Req::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Msg_LoginAccount_Req::password() const {
  // @@protoc_insertion_point(field_get:Msg_LoginAccount_Req.password)
  return password_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Msg_LoginAccount_Req::set_password(const ::std::string& value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Msg_LoginAccount_Req.password)
}
 void Msg_LoginAccount_Req::set_password(const char* value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Msg_LoginAccount_Req.password)
}
 void Msg_LoginAccount_Req::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Msg_LoginAccount_Req.password)
}
 ::std::string* Msg_LoginAccount_Req::mutable_password() {
  
  // @@protoc_insertion_point(field_mutable:Msg_LoginAccount_Req.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Msg_LoginAccount_Req::release_password() {
  // @@protoc_insertion_point(field_release:Msg_LoginAccount_Req.password)
  
  return password_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Msg_LoginAccount_Req::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:Msg_LoginAccount_Req.password)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Msg_LoginAccount_Ack::kReturncodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Msg_LoginAccount_Ack::Msg_LoginAccount_Ack()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Msg_LoginAccount_Ack)
}

void Msg_LoginAccount_Ack::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Msg_LoginAccount_Ack::Msg_LoginAccount_Ack(const Msg_LoginAccount_Ack& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Msg_LoginAccount_Ack)
}

void Msg_LoginAccount_Ack::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  returncode_ = 0;
}

Msg_LoginAccount_Ack::~Msg_LoginAccount_Ack() {
  // @@protoc_insertion_point(destructor:Msg_LoginAccount_Ack)
  SharedDtor();
}

void Msg_LoginAccount_Ack::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Msg_LoginAccount_Ack::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Msg_LoginAccount_Ack::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Msg_LoginAccount_Ack_descriptor_;
}

const Msg_LoginAccount_Ack& Msg_LoginAccount_Ack::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_player_2eproto();
  return *default_instance_;
}

Msg_LoginAccount_Ack* Msg_LoginAccount_Ack::default_instance_ = NULL;

Msg_LoginAccount_Ack* Msg_LoginAccount_Ack::New(::google::protobuf::Arena* arena) const {
  Msg_LoginAccount_Ack* n = new Msg_LoginAccount_Ack;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Msg_LoginAccount_Ack::Clear() {
// @@protoc_insertion_point(message_clear_start:Msg_LoginAccount_Ack)
  returncode_ = 0;
}

bool Msg_LoginAccount_Ack::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Msg_LoginAccount_Ack)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 returncode = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &returncode_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Msg_LoginAccount_Ack)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Msg_LoginAccount_Ack)
  return false;
#undef DO_
}

void Msg_LoginAccount_Ack::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Msg_LoginAccount_Ack)
  // optional int32 returncode = 1;
  if (this->returncode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->returncode(), output);
  }

  // @@protoc_insertion_point(serialize_end:Msg_LoginAccount_Ack)
}

::google::protobuf::uint8* Msg_LoginAccount_Ack::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Msg_LoginAccount_Ack)
  // optional int32 returncode = 1;
  if (this->returncode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->returncode(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Msg_LoginAccount_Ack)
  return target;
}

int Msg_LoginAccount_Ack::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Msg_LoginAccount_Ack)
  int total_size = 0;

  // optional int32 returncode = 1;
  if (this->returncode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->returncode());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Msg_LoginAccount_Ack::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Msg_LoginAccount_Ack)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Msg_LoginAccount_Ack* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Msg_LoginAccount_Ack>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Msg_LoginAccount_Ack)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Msg_LoginAccount_Ack)
    MergeFrom(*source);
  }
}

void Msg_LoginAccount_Ack::MergeFrom(const Msg_LoginAccount_Ack& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Msg_LoginAccount_Ack)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.returncode() != 0) {
    set_returncode(from.returncode());
  }
}

void Msg_LoginAccount_Ack::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Msg_LoginAccount_Ack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Msg_LoginAccount_Ack::CopyFrom(const Msg_LoginAccount_Ack& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Msg_LoginAccount_Ack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_LoginAccount_Ack::IsInitialized() const {

  return true;
}

void Msg_LoginAccount_Ack::Swap(Msg_LoginAccount_Ack* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Msg_LoginAccount_Ack::InternalSwap(Msg_LoginAccount_Ack* other) {
  std::swap(returncode_, other->returncode_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Msg_LoginAccount_Ack::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Msg_LoginAccount_Ack_descriptor_;
  metadata.reflection = Msg_LoginAccount_Ack_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Msg_LoginAccount_Ack

// optional int32 returncode = 1;
void Msg_LoginAccount_Ack::clear_returncode() {
  returncode_ = 0;
}
 ::google::protobuf::int32 Msg_LoginAccount_Ack::returncode() const {
  // @@protoc_insertion_point(field_get:Msg_LoginAccount_Ack.returncode)
  return returncode_;
}
 void Msg_LoginAccount_Ack::set_returncode(::google::protobuf::int32 value) {
  
  returncode_ = value;
  // @@protoc_insertion_point(field_set:Msg_LoginAccount_Ack.returncode)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Msg_LoginPlayer_Req::kRoleidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Msg_LoginPlayer_Req::Msg_LoginPlayer_Req()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Msg_LoginPlayer_Req)
}

void Msg_LoginPlayer_Req::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Msg_LoginPlayer_Req::Msg_LoginPlayer_Req(const Msg_LoginPlayer_Req& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Msg_LoginPlayer_Req)
}

void Msg_LoginPlayer_Req::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  roleid_ = GOOGLE_ULONGLONG(0);
}

Msg_LoginPlayer_Req::~Msg_LoginPlayer_Req() {
  // @@protoc_insertion_point(destructor:Msg_LoginPlayer_Req)
  SharedDtor();
}

void Msg_LoginPlayer_Req::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Msg_LoginPlayer_Req::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Msg_LoginPlayer_Req::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Msg_LoginPlayer_Req_descriptor_;
}

const Msg_LoginPlayer_Req& Msg_LoginPlayer_Req::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_player_2eproto();
  return *default_instance_;
}

Msg_LoginPlayer_Req* Msg_LoginPlayer_Req::default_instance_ = NULL;

Msg_LoginPlayer_Req* Msg_LoginPlayer_Req::New(::google::protobuf::Arena* arena) const {
  Msg_LoginPlayer_Req* n = new Msg_LoginPlayer_Req;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Msg_LoginPlayer_Req::Clear() {
// @@protoc_insertion_point(message_clear_start:Msg_LoginPlayer_Req)
  roleid_ = GOOGLE_ULONGLONG(0);
}

bool Msg_LoginPlayer_Req::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Msg_LoginPlayer_Req)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint64 roleid = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &roleid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Msg_LoginPlayer_Req)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Msg_LoginPlayer_Req)
  return false;
#undef DO_
}

void Msg_LoginPlayer_Req::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Msg_LoginPlayer_Req)
  // optional uint64 roleid = 1;
  if (this->roleid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->roleid(), output);
  }

  // @@protoc_insertion_point(serialize_end:Msg_LoginPlayer_Req)
}

::google::protobuf::uint8* Msg_LoginPlayer_Req::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Msg_LoginPlayer_Req)
  // optional uint64 roleid = 1;
  if (this->roleid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->roleid(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Msg_LoginPlayer_Req)
  return target;
}

int Msg_LoginPlayer_Req::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Msg_LoginPlayer_Req)
  int total_size = 0;

  // optional uint64 roleid = 1;
  if (this->roleid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->roleid());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Msg_LoginPlayer_Req::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Msg_LoginPlayer_Req)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Msg_LoginPlayer_Req* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Msg_LoginPlayer_Req>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Msg_LoginPlayer_Req)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Msg_LoginPlayer_Req)
    MergeFrom(*source);
  }
}

void Msg_LoginPlayer_Req::MergeFrom(const Msg_LoginPlayer_Req& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Msg_LoginPlayer_Req)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.roleid() != 0) {
    set_roleid(from.roleid());
  }
}

void Msg_LoginPlayer_Req::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Msg_LoginPlayer_Req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Msg_LoginPlayer_Req::CopyFrom(const Msg_LoginPlayer_Req& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Msg_LoginPlayer_Req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_LoginPlayer_Req::IsInitialized() const {

  return true;
}

void Msg_LoginPlayer_Req::Swap(Msg_LoginPlayer_Req* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Msg_LoginPlayer_Req::InternalSwap(Msg_LoginPlayer_Req* other) {
  std::swap(roleid_, other->roleid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Msg_LoginPlayer_Req::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Msg_LoginPlayer_Req_descriptor_;
  metadata.reflection = Msg_LoginPlayer_Req_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Msg_LoginPlayer_Req

// optional uint64 roleid = 1;
void Msg_LoginPlayer_Req::clear_roleid() {
  roleid_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 Msg_LoginPlayer_Req::roleid() const {
  // @@protoc_insertion_point(field_get:Msg_LoginPlayer_Req.roleid)
  return roleid_;
}
 void Msg_LoginPlayer_Req::set_roleid(::google::protobuf::uint64 value) {
  
  roleid_ = value;
  // @@protoc_insertion_point(field_set:Msg_LoginPlayer_Req.roleid)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Msg_LoginPlayer_Ack::kReturncodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Msg_LoginPlayer_Ack::Msg_LoginPlayer_Ack()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Msg_LoginPlayer_Ack)
}

void Msg_LoginPlayer_Ack::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Msg_LoginPlayer_Ack::Msg_LoginPlayer_Ack(const Msg_LoginPlayer_Ack& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Msg_LoginPlayer_Ack)
}

void Msg_LoginPlayer_Ack::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  returncode_ = 0;
}

Msg_LoginPlayer_Ack::~Msg_LoginPlayer_Ack() {
  // @@protoc_insertion_point(destructor:Msg_LoginPlayer_Ack)
  SharedDtor();
}

void Msg_LoginPlayer_Ack::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Msg_LoginPlayer_Ack::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Msg_LoginPlayer_Ack::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Msg_LoginPlayer_Ack_descriptor_;
}

const Msg_LoginPlayer_Ack& Msg_LoginPlayer_Ack::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_player_2eproto();
  return *default_instance_;
}

Msg_LoginPlayer_Ack* Msg_LoginPlayer_Ack::default_instance_ = NULL;

Msg_LoginPlayer_Ack* Msg_LoginPlayer_Ack::New(::google::protobuf::Arena* arena) const {
  Msg_LoginPlayer_Ack* n = new Msg_LoginPlayer_Ack;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Msg_LoginPlayer_Ack::Clear() {
// @@protoc_insertion_point(message_clear_start:Msg_LoginPlayer_Ack)
  returncode_ = 0;
}

bool Msg_LoginPlayer_Ack::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Msg_LoginPlayer_Ack)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 returncode = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &returncode_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Msg_LoginPlayer_Ack)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Msg_LoginPlayer_Ack)
  return false;
#undef DO_
}

void Msg_LoginPlayer_Ack::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Msg_LoginPlayer_Ack)
  // optional int32 returncode = 1;
  if (this->returncode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->returncode(), output);
  }

  // @@protoc_insertion_point(serialize_end:Msg_LoginPlayer_Ack)
}

::google::protobuf::uint8* Msg_LoginPlayer_Ack::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Msg_LoginPlayer_Ack)
  // optional int32 returncode = 1;
  if (this->returncode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->returncode(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Msg_LoginPlayer_Ack)
  return target;
}

int Msg_LoginPlayer_Ack::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Msg_LoginPlayer_Ack)
  int total_size = 0;

  // optional int32 returncode = 1;
  if (this->returncode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->returncode());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Msg_LoginPlayer_Ack::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Msg_LoginPlayer_Ack)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Msg_LoginPlayer_Ack* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Msg_LoginPlayer_Ack>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Msg_LoginPlayer_Ack)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Msg_LoginPlayer_Ack)
    MergeFrom(*source);
  }
}

void Msg_LoginPlayer_Ack::MergeFrom(const Msg_LoginPlayer_Ack& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Msg_LoginPlayer_Ack)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.returncode() != 0) {
    set_returncode(from.returncode());
  }
}

void Msg_LoginPlayer_Ack::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Msg_LoginPlayer_Ack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Msg_LoginPlayer_Ack::CopyFrom(const Msg_LoginPlayer_Ack& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Msg_LoginPlayer_Ack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_LoginPlayer_Ack::IsInitialized() const {

  return true;
}

void Msg_LoginPlayer_Ack::Swap(Msg_LoginPlayer_Ack* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Msg_LoginPlayer_Ack::InternalSwap(Msg_LoginPlayer_Ack* other) {
  std::swap(returncode_, other->returncode_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Msg_LoginPlayer_Ack::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Msg_LoginPlayer_Ack_descriptor_;
  metadata.reflection = Msg_LoginPlayer_Ack_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Msg_LoginPlayer_Ack

// optional int32 returncode = 1;
void Msg_LoginPlayer_Ack::clear_returncode() {
  returncode_ = 0;
}
 ::google::protobuf::int32 Msg_LoginPlayer_Ack::returncode() const {
  // @@protoc_insertion_point(field_get:Msg_LoginPlayer_Ack.returncode)
  return returncode_;
}
 void Msg_LoginPlayer_Ack::set_returncode(::google::protobuf::int32 value) {
  
  returncode_ = value;
  // @@protoc_insertion_point(field_set:Msg_LoginPlayer_Ack.returncode)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Msg_CreatePlayer_Req::kAccountidFieldNumber;
const int Msg_CreatePlayer_Req::kNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Msg_CreatePlayer_Req::Msg_CreatePlayer_Req()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Msg_CreatePlayer_Req)
}

void Msg_CreatePlayer_Req::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Msg_CreatePlayer_Req::Msg_CreatePlayer_Req(const Msg_CreatePlayer_Req& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Msg_CreatePlayer_Req)
}

void Msg_CreatePlayer_Req::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  accountid_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Msg_CreatePlayer_Req::~Msg_CreatePlayer_Req() {
  // @@protoc_insertion_point(destructor:Msg_CreatePlayer_Req)
  SharedDtor();
}

void Msg_CreatePlayer_Req::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void Msg_CreatePlayer_Req::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Msg_CreatePlayer_Req::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Msg_CreatePlayer_Req_descriptor_;
}

const Msg_CreatePlayer_Req& Msg_CreatePlayer_Req::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_player_2eproto();
  return *default_instance_;
}

Msg_CreatePlayer_Req* Msg_CreatePlayer_Req::default_instance_ = NULL;

Msg_CreatePlayer_Req* Msg_CreatePlayer_Req::New(::google::protobuf::Arena* arena) const {
  Msg_CreatePlayer_Req* n = new Msg_CreatePlayer_Req;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Msg_CreatePlayer_Req::Clear() {
// @@protoc_insertion_point(message_clear_start:Msg_CreatePlayer_Req)
  accountid_ = 0;
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool Msg_CreatePlayer_Req::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Msg_CreatePlayer_Req)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 accountid = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &accountid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_name;
        break;
      }

      // optional string name = 2;
      case 2: {
        if (tag == 18) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Msg_CreatePlayer_Req.name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Msg_CreatePlayer_Req)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Msg_CreatePlayer_Req)
  return false;
#undef DO_
}

void Msg_CreatePlayer_Req::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Msg_CreatePlayer_Req)
  // optional int32 accountid = 1;
  if (this->accountid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->accountid(), output);
  }

  // optional string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Msg_CreatePlayer_Req.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->name(), output);
  }

  // @@protoc_insertion_point(serialize_end:Msg_CreatePlayer_Req)
}

::google::protobuf::uint8* Msg_CreatePlayer_Req::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Msg_CreatePlayer_Req)
  // optional int32 accountid = 1;
  if (this->accountid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->accountid(), target);
  }

  // optional string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Msg_CreatePlayer_Req.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Msg_CreatePlayer_Req)
  return target;
}

int Msg_CreatePlayer_Req::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Msg_CreatePlayer_Req)
  int total_size = 0;

  // optional int32 accountid = 1;
  if (this->accountid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->accountid());
  }

  // optional string name = 2;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Msg_CreatePlayer_Req::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Msg_CreatePlayer_Req)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Msg_CreatePlayer_Req* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Msg_CreatePlayer_Req>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Msg_CreatePlayer_Req)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Msg_CreatePlayer_Req)
    MergeFrom(*source);
  }
}

void Msg_CreatePlayer_Req::MergeFrom(const Msg_CreatePlayer_Req& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Msg_CreatePlayer_Req)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.accountid() != 0) {
    set_accountid(from.accountid());
  }
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
}

void Msg_CreatePlayer_Req::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Msg_CreatePlayer_Req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Msg_CreatePlayer_Req::CopyFrom(const Msg_CreatePlayer_Req& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Msg_CreatePlayer_Req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_CreatePlayer_Req::IsInitialized() const {

  return true;
}

void Msg_CreatePlayer_Req::Swap(Msg_CreatePlayer_Req* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Msg_CreatePlayer_Req::InternalSwap(Msg_CreatePlayer_Req* other) {
  std::swap(accountid_, other->accountid_);
  name_.Swap(&other->name_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Msg_CreatePlayer_Req::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Msg_CreatePlayer_Req_descriptor_;
  metadata.reflection = Msg_CreatePlayer_Req_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Msg_CreatePlayer_Req

// optional int32 accountid = 1;
void Msg_CreatePlayer_Req::clear_accountid() {
  accountid_ = 0;
}
 ::google::protobuf::int32 Msg_CreatePlayer_Req::accountid() const {
  // @@protoc_insertion_point(field_get:Msg_CreatePlayer_Req.accountid)
  return accountid_;
}
 void Msg_CreatePlayer_Req::set_accountid(::google::protobuf::int32 value) {
  
  accountid_ = value;
  // @@protoc_insertion_point(field_set:Msg_CreatePlayer_Req.accountid)
}

// optional string name = 2;
void Msg_CreatePlayer_Req::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Msg_CreatePlayer_Req::name() const {
  // @@protoc_insertion_point(field_get:Msg_CreatePlayer_Req.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Msg_CreatePlayer_Req::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Msg_CreatePlayer_Req.name)
}
 void Msg_CreatePlayer_Req::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Msg_CreatePlayer_Req.name)
}
 void Msg_CreatePlayer_Req::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Msg_CreatePlayer_Req.name)
}
 ::std::string* Msg_CreatePlayer_Req::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:Msg_CreatePlayer_Req.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Msg_CreatePlayer_Req::release_name() {
  // @@protoc_insertion_point(field_release:Msg_CreatePlayer_Req.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Msg_CreatePlayer_Req::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:Msg_CreatePlayer_Req.name)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Msg_CreatePlayer_Ack::kReturncodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Msg_CreatePlayer_Ack::Msg_CreatePlayer_Ack()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Msg_CreatePlayer_Ack)
}

void Msg_CreatePlayer_Ack::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Msg_CreatePlayer_Ack::Msg_CreatePlayer_Ack(const Msg_CreatePlayer_Ack& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Msg_CreatePlayer_Ack)
}

void Msg_CreatePlayer_Ack::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  returncode_ = 0;
}

Msg_CreatePlayer_Ack::~Msg_CreatePlayer_Ack() {
  // @@protoc_insertion_point(destructor:Msg_CreatePlayer_Ack)
  SharedDtor();
}

void Msg_CreatePlayer_Ack::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Msg_CreatePlayer_Ack::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Msg_CreatePlayer_Ack::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Msg_CreatePlayer_Ack_descriptor_;
}

const Msg_CreatePlayer_Ack& Msg_CreatePlayer_Ack::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_player_2eproto();
  return *default_instance_;
}

Msg_CreatePlayer_Ack* Msg_CreatePlayer_Ack::default_instance_ = NULL;

Msg_CreatePlayer_Ack* Msg_CreatePlayer_Ack::New(::google::protobuf::Arena* arena) const {
  Msg_CreatePlayer_Ack* n = new Msg_CreatePlayer_Ack;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Msg_CreatePlayer_Ack::Clear() {
// @@protoc_insertion_point(message_clear_start:Msg_CreatePlayer_Ack)
  returncode_ = 0;
}

bool Msg_CreatePlayer_Ack::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Msg_CreatePlayer_Ack)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 returncode = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &returncode_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Msg_CreatePlayer_Ack)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Msg_CreatePlayer_Ack)
  return false;
#undef DO_
}

void Msg_CreatePlayer_Ack::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Msg_CreatePlayer_Ack)
  // optional int32 returncode = 1;
  if (this->returncode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->returncode(), output);
  }

  // @@protoc_insertion_point(serialize_end:Msg_CreatePlayer_Ack)
}

::google::protobuf::uint8* Msg_CreatePlayer_Ack::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Msg_CreatePlayer_Ack)
  // optional int32 returncode = 1;
  if (this->returncode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->returncode(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Msg_CreatePlayer_Ack)
  return target;
}

int Msg_CreatePlayer_Ack::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Msg_CreatePlayer_Ack)
  int total_size = 0;

  // optional int32 returncode = 1;
  if (this->returncode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->returncode());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Msg_CreatePlayer_Ack::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Msg_CreatePlayer_Ack)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Msg_CreatePlayer_Ack* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Msg_CreatePlayer_Ack>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Msg_CreatePlayer_Ack)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Msg_CreatePlayer_Ack)
    MergeFrom(*source);
  }
}

void Msg_CreatePlayer_Ack::MergeFrom(const Msg_CreatePlayer_Ack& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Msg_CreatePlayer_Ack)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.returncode() != 0) {
    set_returncode(from.returncode());
  }
}

void Msg_CreatePlayer_Ack::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Msg_CreatePlayer_Ack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Msg_CreatePlayer_Ack::CopyFrom(const Msg_CreatePlayer_Ack& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Msg_CreatePlayer_Ack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_CreatePlayer_Ack::IsInitialized() const {

  return true;
}

void Msg_CreatePlayer_Ack::Swap(Msg_CreatePlayer_Ack* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Msg_CreatePlayer_Ack::InternalSwap(Msg_CreatePlayer_Ack* other) {
  std::swap(returncode_, other->returncode_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Msg_CreatePlayer_Ack::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Msg_CreatePlayer_Ack_descriptor_;
  metadata.reflection = Msg_CreatePlayer_Ack_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Msg_CreatePlayer_Ack

// optional int32 returncode = 1;
void Msg_CreatePlayer_Ack::clear_returncode() {
  returncode_ = 0;
}
 ::google::protobuf::int32 Msg_CreatePlayer_Ack::returncode() const {
  // @@protoc_insertion_point(field_get:Msg_CreatePlayer_Ack.returncode)
  return returncode_;
}
 void Msg_CreatePlayer_Ack::set_returncode(::google::protobuf::int32 value) {
  
  returncode_ = value;
  // @@protoc_insertion_point(field_set:Msg_CreatePlayer_Ack.returncode)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Msg_LoginOff_Req::kRoleidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Msg_LoginOff_Req::Msg_LoginOff_Req()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Msg_LoginOff_Req)
}

void Msg_LoginOff_Req::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Msg_LoginOff_Req::Msg_LoginOff_Req(const Msg_LoginOff_Req& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Msg_LoginOff_Req)
}

void Msg_LoginOff_Req::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  roleid_ = 0;
}

Msg_LoginOff_Req::~Msg_LoginOff_Req() {
  // @@protoc_insertion_point(destructor:Msg_LoginOff_Req)
  SharedDtor();
}

void Msg_LoginOff_Req::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Msg_LoginOff_Req::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Msg_LoginOff_Req::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Msg_LoginOff_Req_descriptor_;
}

const Msg_LoginOff_Req& Msg_LoginOff_Req::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_player_2eproto();
  return *default_instance_;
}

Msg_LoginOff_Req* Msg_LoginOff_Req::default_instance_ = NULL;

Msg_LoginOff_Req* Msg_LoginOff_Req::New(::google::protobuf::Arena* arena) const {
  Msg_LoginOff_Req* n = new Msg_LoginOff_Req;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Msg_LoginOff_Req::Clear() {
// @@protoc_insertion_point(message_clear_start:Msg_LoginOff_Req)
  roleid_ = 0;
}

bool Msg_LoginOff_Req::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Msg_LoginOff_Req)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 roleid = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &roleid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Msg_LoginOff_Req)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Msg_LoginOff_Req)
  return false;
#undef DO_
}

void Msg_LoginOff_Req::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Msg_LoginOff_Req)
  // optional int32 roleid = 1;
  if (this->roleid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->roleid(), output);
  }

  // @@protoc_insertion_point(serialize_end:Msg_LoginOff_Req)
}

::google::protobuf::uint8* Msg_LoginOff_Req::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Msg_LoginOff_Req)
  // optional int32 roleid = 1;
  if (this->roleid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->roleid(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Msg_LoginOff_Req)
  return target;
}

int Msg_LoginOff_Req::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Msg_LoginOff_Req)
  int total_size = 0;

  // optional int32 roleid = 1;
  if (this->roleid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->roleid());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Msg_LoginOff_Req::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Msg_LoginOff_Req)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Msg_LoginOff_Req* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Msg_LoginOff_Req>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Msg_LoginOff_Req)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Msg_LoginOff_Req)
    MergeFrom(*source);
  }
}

void Msg_LoginOff_Req::MergeFrom(const Msg_LoginOff_Req& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Msg_LoginOff_Req)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.roleid() != 0) {
    set_roleid(from.roleid());
  }
}

void Msg_LoginOff_Req::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Msg_LoginOff_Req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Msg_LoginOff_Req::CopyFrom(const Msg_LoginOff_Req& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Msg_LoginOff_Req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_LoginOff_Req::IsInitialized() const {

  return true;
}

void Msg_LoginOff_Req::Swap(Msg_LoginOff_Req* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Msg_LoginOff_Req::InternalSwap(Msg_LoginOff_Req* other) {
  std::swap(roleid_, other->roleid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Msg_LoginOff_Req::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Msg_LoginOff_Req_descriptor_;
  metadata.reflection = Msg_LoginOff_Req_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Msg_LoginOff_Req

// optional int32 roleid = 1;
void Msg_LoginOff_Req::clear_roleid() {
  roleid_ = 0;
}
 ::google::protobuf::int32 Msg_LoginOff_Req::roleid() const {
  // @@protoc_insertion_point(field_get:Msg_LoginOff_Req.roleid)
  return roleid_;
}
 void Msg_LoginOff_Req::set_roleid(::google::protobuf::int32 value) {
  
  roleid_ = value;
  // @@protoc_insertion_point(field_set:Msg_LoginOff_Req.roleid)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Msg_LoginOff_Ack::kReturncodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Msg_LoginOff_Ack::Msg_LoginOff_Ack()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Msg_LoginOff_Ack)
}

void Msg_LoginOff_Ack::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Msg_LoginOff_Ack::Msg_LoginOff_Ack(const Msg_LoginOff_Ack& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Msg_LoginOff_Ack)
}

void Msg_LoginOff_Ack::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  returncode_ = 0;
}

Msg_LoginOff_Ack::~Msg_LoginOff_Ack() {
  // @@protoc_insertion_point(destructor:Msg_LoginOff_Ack)
  SharedDtor();
}

void Msg_LoginOff_Ack::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Msg_LoginOff_Ack::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Msg_LoginOff_Ack::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Msg_LoginOff_Ack_descriptor_;
}

const Msg_LoginOff_Ack& Msg_LoginOff_Ack::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_player_2eproto();
  return *default_instance_;
}

Msg_LoginOff_Ack* Msg_LoginOff_Ack::default_instance_ = NULL;

Msg_LoginOff_Ack* Msg_LoginOff_Ack::New(::google::protobuf::Arena* arena) const {
  Msg_LoginOff_Ack* n = new Msg_LoginOff_Ack;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Msg_LoginOff_Ack::Clear() {
// @@protoc_insertion_point(message_clear_start:Msg_LoginOff_Ack)
  returncode_ = 0;
}

bool Msg_LoginOff_Ack::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Msg_LoginOff_Ack)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 returncode = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &returncode_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Msg_LoginOff_Ack)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Msg_LoginOff_Ack)
  return false;
#undef DO_
}

void Msg_LoginOff_Ack::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Msg_LoginOff_Ack)
  // optional int32 returncode = 1;
  if (this->returncode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->returncode(), output);
  }

  // @@protoc_insertion_point(serialize_end:Msg_LoginOff_Ack)
}

::google::protobuf::uint8* Msg_LoginOff_Ack::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Msg_LoginOff_Ack)
  // optional int32 returncode = 1;
  if (this->returncode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->returncode(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Msg_LoginOff_Ack)
  return target;
}

int Msg_LoginOff_Ack::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Msg_LoginOff_Ack)
  int total_size = 0;

  // optional int32 returncode = 1;
  if (this->returncode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->returncode());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Msg_LoginOff_Ack::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Msg_LoginOff_Ack)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Msg_LoginOff_Ack* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Msg_LoginOff_Ack>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Msg_LoginOff_Ack)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Msg_LoginOff_Ack)
    MergeFrom(*source);
  }
}

void Msg_LoginOff_Ack::MergeFrom(const Msg_LoginOff_Ack& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Msg_LoginOff_Ack)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.returncode() != 0) {
    set_returncode(from.returncode());
  }
}

void Msg_LoginOff_Ack::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Msg_LoginOff_Ack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Msg_LoginOff_Ack::CopyFrom(const Msg_LoginOff_Ack& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Msg_LoginOff_Ack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Msg_LoginOff_Ack::IsInitialized() const {

  return true;
}

void Msg_LoginOff_Ack::Swap(Msg_LoginOff_Ack* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Msg_LoginOff_Ack::InternalSwap(Msg_LoginOff_Ack* other) {
  std::swap(returncode_, other->returncode_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Msg_LoginOff_Ack::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Msg_LoginOff_Ack_descriptor_;
  metadata.reflection = Msg_LoginOff_Ack_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Msg_LoginOff_Ack

// optional int32 returncode = 1;
void Msg_LoginOff_Ack::clear_returncode() {
  returncode_ = 0;
}
 ::google::protobuf::int32 Msg_LoginOff_Ack::returncode() const {
  // @@protoc_insertion_point(field_get:Msg_LoginOff_Ack.returncode)
  return returncode_;
}
 void Msg_LoginOff_Ack::set_returncode(::google::protobuf::int32 value) {
  
  returncode_ = value;
  // @@protoc_insertion_point(field_set:Msg_LoginOff_Ack.returncode)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
